/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 17-jun.-2025 22:43:44 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Cliente_Rol]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Cliente] DROP CONSTRAINT [FK_Cliente_Rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ComprobanteDePago_Pedidoonline]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ComprobanteDePago] DROP CONSTRAINT [FK_ComprobanteDePago_Pedidoonline]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PedidoOnline_Cliente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedidoonline] DROP CONSTRAINT [FK_PedidoOnline_Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PedidoOnline_Estado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedidoonline] DROP CONSTRAINT [FK_PedidoOnline_Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PedidoOnline_Formaenvio]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedidoonline] DROP CONSTRAINT [FK_PedidoOnline_Formaenvio]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_PedidoOnline_MetodoDePago]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Pedidoonline] DROP CONSTRAINT [FK_PedidoOnline_MetodoDePago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Categoria]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto] DROP CONSTRAINT [FK_Producto_Categoria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Marca]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto] DROP CONSTRAINT [FK_Producto_Marca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto_Tamaño]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto] DROP CONSTRAINT [FK_Producto_Tamaño]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto PedidoOnline_PedidoOnline]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto PedidoOnline] DROP CONSTRAINT [FK_Producto PedidoOnline_PedidoOnline]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Producto PedidoOnline_Producto ]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Producto PedidoOnline] DROP CONSTRAINT [FK_Producto PedidoOnline_Producto ]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Categoria]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Categoria]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Cliente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Cliente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ComprobanteDePago]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ComprobanteDePago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Estado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Formaenvio]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Formaenvio]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Marca]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Marca]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[MetodoDePago]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [MetodoDePago]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pedidoonline]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pedidoonline]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Producto PedidoOnline]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Producto PedidoOnline]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Rol]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Tamaño]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Tamaño]
GO

/* Create Tables */

CREATE TABLE [Categoria]
(
	[idCategoria] int NOT NULL,
	[nombreCategoria] varchar(100) NOT NULL,
	[estado] int NOT NULL
)
GO

CREATE TABLE [Cliente]
(
	[dni] varchar(8) NULL,
	[idCliente] int NOT NULL,
	[nombreCli] varchar(100) NULL,
	[apellidoCli] varchar(100) NULL,
	[correo] varchar(100) NOT NULL,
	[contraseña] varchar(100) NOT NULL,
	[ruc] varchar(11) NULL,
	[razonSocial] varchar(200) NULL,
	[direccion] varchar(200) NULL,
	[telefono] varchar(11) NULL,
	[idRol] int NOT NULL
)
GO

CREATE TABLE [ComprobanteDePago]
(
	[fecha] date NOT NULL,
	[idComprobantePago] int NOT NULL,
	[hora] time(7) NOT NULL,
	[monto] decimal(18) NOT NULL,
	[idPedidoOnline] int NOT NULL
)
GO

CREATE TABLE [Estado]
(
	[idEstado] int NOT NULL,
	[nombreEstado] varchar(50) NOT NULL,
	[estado] int NOT NULL
)
GO

CREATE TABLE [Formaenvio]
(
	[idFormaEnvio] int NOT NULL,
	[nombreForma] varchar(50) NOT NULL,
	[estado] int NOT NULL
)
GO

CREATE TABLE [Marca]
(
	[idMarca] int NOT NULL,
	[nombreMarca] varchar(100) NOT NULL,
	[estado] int NULL
)
GO

CREATE TABLE [MetodoDePago]
(
	[idMetodoPago] int NOT NULL,
	[nombreMetodo] varchar(100) NOT NULL,
	[estado] int NOT NULL
)
GO

CREATE TABLE [Pedidoonline]
(
	[idPedidoOnline] int NOT NULL,
	[idCliente] int NOT NULL,
	[idEstado] int NOT NULL,
	[idFormaEnvio] int NOT NULL,
	[idMetodoPago] int NOT NULL,
	[fecha] date NOT NULL,
	[hora] time(7) NOT NULL,
	[observaciones] varchar(250) NULL
)
GO

CREATE TABLE [Producto]
(
	[idProducto] int NOT NULL,
	[idCategoria] int NOT NULL,
	[idMarca] int NOT NULL,
	[idTamaño] int NOT NULL,
	[nombreProducto] varchar(100) NOT NULL,
	[precioVenta] decimal(4) NOT NULL,
	[stock] int NOT NULL,
	[estado] int NOT NULL,
	[descripcionP] varchar(200) NULL
)
GO

CREATE TABLE [Producto PedidoOnline]
(
	[idPedidoOnline] int NOT NULL,
	[cantidad] int NOT NULL,
	[idProducto] int NOT NULL,
	[idPedidoDetalle] int NOT NULL,
	[precioUnitario] decimal(18) NOT NULL,
	[subtotal] decimal(18) NOT NULL
)
GO

CREATE TABLE [Rol]
(
	[idRol] int NOT NULL,
	[nombreRol] varchar(50) NOT NULL
)
GO

CREATE TABLE [Tamaño]
(
	[idTamaño] int NOT NULL,
	[nombre] varchar(100) NOT NULL,
	[estado] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Categoria] 
 ADD CONSTRAINT [PK_Categoria]
	PRIMARY KEY CLUSTERED ([idCategoria] ASC)
GO

ALTER TABLE [Cliente] 
 ADD CONSTRAINT [PK_Cliente]
	PRIMARY KEY CLUSTERED ([idCliente] ASC)
GO

ALTER TABLE [ComprobanteDePago] 
 ADD CONSTRAINT [PK_ComprobanteDePago]
	PRIMARY KEY CLUSTERED ([idComprobantePago] ASC)
GO

ALTER TABLE [Estado] 
 ADD CONSTRAINT [PK_Estado]
	PRIMARY KEY CLUSTERED ([idEstado] ASC)
GO

ALTER TABLE [Formaenvio] 
 ADD CONSTRAINT [PK_Formaenvio]
	PRIMARY KEY CLUSTERED ([idFormaEnvio] ASC)
GO

ALTER TABLE [Marca] 
 ADD CONSTRAINT [PK_Marca]
	PRIMARY KEY CLUSTERED ([idMarca] ASC)
GO

ALTER TABLE [MetodoDePago] 
 ADD CONSTRAINT [PK_MetodoDePago]
	PRIMARY KEY CLUSTERED ([idMetodoPago] ASC)
GO

ALTER TABLE [Pedidoonline] 
 ADD CONSTRAINT [PK_PedidoOnline]
	PRIMARY KEY CLUSTERED ([idPedidoOnline] ASC)
GO

ALTER TABLE [Producto] 
 ADD CONSTRAINT [PK_Producto]
	PRIMARY KEY CLUSTERED ([idProducto] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Producto_Categoria] 
 ON [Producto] ([idCategoria] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Producto_Marca] 
 ON [Producto] ([idMarca] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Producto_Tamaño] 
 ON [Producto] ([idTamaño] ASC)
GO

ALTER TABLE [Producto PedidoOnline] 
 ADD CONSTRAINT [PK_Producto PedidoOnline]
	PRIMARY KEY CLUSTERED ([idPedidoDetalle] ASC)
GO

ALTER TABLE [Rol] 
 ADD CONSTRAINT [PK_Rol]
	PRIMARY KEY CLUSTERED ([idRol] ASC)
GO

ALTER TABLE [Tamaño] 
 ADD CONSTRAINT [PK_Tamaño]
	PRIMARY KEY CLUSTERED ([idTamaño] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Cliente] ADD CONSTRAINT [FK_Cliente_Rol]
	FOREIGN KEY ([idRol]) REFERENCES [Rol] ([idRol]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ComprobanteDePago] ADD CONSTRAINT [FK_ComprobanteDePago_Pedidoonline]
	FOREIGN KEY ([idPedidoOnline]) REFERENCES [Pedidoonline] ([idPedidoOnline]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedidoonline] ADD CONSTRAINT [FK_PedidoOnline_Cliente]
	FOREIGN KEY ([idCliente]) REFERENCES [Cliente] ([idCliente]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedidoonline] ADD CONSTRAINT [FK_PedidoOnline_Estado]
	FOREIGN KEY ([idEstado]) REFERENCES [Estado] ([idEstado]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedidoonline] ADD CONSTRAINT [FK_PedidoOnline_Formaenvio]
	FOREIGN KEY ([idFormaEnvio]) REFERENCES [Formaenvio] ([idFormaEnvio]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Pedidoonline] ADD CONSTRAINT [FK_PedidoOnline_MetodoDePago]
	FOREIGN KEY ([idMetodoPago]) REFERENCES [MetodoDePago] ([idMetodoPago]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto] ADD CONSTRAINT [FK_Producto_Categoria]
	FOREIGN KEY ([idCategoria]) REFERENCES [Categoria] ([idCategoria]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto] ADD CONSTRAINT [FK_Producto_Marca]
	FOREIGN KEY ([idMarca]) REFERENCES [Marca] ([idMarca]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto] ADD CONSTRAINT [FK_Producto_Tamaño]
	FOREIGN KEY ([idTamaño]) REFERENCES [Tamaño] ([idTamaño]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto PedidoOnline] ADD CONSTRAINT [FK_Producto PedidoOnline_PedidoOnline]
	FOREIGN KEY ([idPedidoOnline]) REFERENCES [Pedidoonline] ([idPedidoOnline]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Producto PedidoOnline] ADD CONSTRAINT [FK_Producto PedidoOnline_Producto ]
	FOREIGN KEY ([idProducto]) REFERENCES [Producto] ([idProducto]) ON DELETE No Action ON UPDATE No Action
GO
